theme = "ayu_mirage"

[editor]
line-number = "relative"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[keys.normal]
"C-s" = [":format", ":w"]
"S-esc" = ":quit"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
"C-j" = "save_selection"
"C-left" = "move_prev_word_start"
"C-right" = "move_next_word_end"

[keys.insert]
"C-s" = [":format", ":w"]
"S-esc" = ":quit"
"C-left" = "move_prev_word_start"
"C-right" = "move_next_word_end"
"j" = { "k" = "normal_mode" }

[keys.select]
"C-s" = [":format", ":w"]
"S-esc" = ":quit"
