[skin]
default = "#b3b1ad None"
tree = "#59c2ff None"
parent = "#5c6773 None"
file = "#b3b1ad None"
directory = "#ffb454 None Bold"
exe = "#b8cc52 None"
link = "#95e6cb None"
pruning = "#5c6773 None Italic"
perm__ = "#5c6773 None"
perm_r = "#59c2ff None"
perm_w = "#ffb454 None"
perm_x = "#b8cc52 None"
owner = "#d2a6ff None"
group = "#95e6cb None"
count = "#ff8f40 None"
dates = "#5c6773 None"
sparse = "#ff8f40 None"
content_extract = "#95e6cb None"
content_match = "#ffb454 None Bold"
device_id_major = "#d2a6ff None"
device_id_sep = "#5c6773 None"
device_id_minor = "#d2a6ff None"
git_branch = "#d2a6ff None"
git_insertions = "#b8cc52 None"
git_deletions = "#f07178 None"
git_status_current = "#5c6773 None"
git_status_modified = "#ffb454 None"
git_status_new = "#b8cc52 None Bold"
git_status_ignored = "#5c6773 None"
git_status_conflicted = "#f07178 None Bold"
git_status_other = "#ff8f40 None"
selected_line = "None #1f2430"
char_match = "#ffb454 None Bold"
file_error = "#f07178 None Bold"
flag_label = "#5c6773 None"
flag_value = "#ff8f40 None Bold"
input = "#b3b1ad None / #b3b1ad #0f1419"
status_error = "#0b0e14 #f07178 Bold"
status_job = "#0b0e14 #ffb454"
status_normal = "#b3b1ad #0f1419"
status_italic = "#95e6cb #0f1419 Italic"
status_bold = "#ffb454 #0f1419 Bold"
status_code = "#d2a6ff #0f1419"
status_ellipsis = "#5c6773 #0f1419"
purpose_normal = "#b3b1ad None"
purpose_italic = "#95e6cb None Italic"
purpose_bold = "#ffb454 None Bold"
purpose_ellipsis = "#5c6773 None"
scrollbar_track = "#1f2430 None"
scrollbar_thumb = "#5c6773 None"
help_paragraph = "#b3b1ad None"
help_bold = "#ffb454 None Bold"
help_italic = "#95e6cb None Italic"
help_code = "#d2a6ff #0f1419"
help_headers = "#ff8f40 None Bold"
help_table_border = "#5c6773 None"
preview_title = "#ffb454 None Bold"
preview = "#b3b1ad #0f1419"
preview_line_number = "#5c6773 #0f1419"
preview_match = "None #32415e"
preview_separator = "#59c2ff None"
hex_null = "#5c6773 None"
hex_ascii_graphic = "#b3b1ad None"
hex_ascii_whitespace = "#ffb454 None"
hex_ascii_other = "#ff8f40 None"
hex_non_ascii = "#f07178 None"
staging_area_title = "#ffb454 None Bold"
mode_command_mark = "#0b0e14 #ff8f40 Bold"
good_to_bad_0 = "#b8cc52 None"
good_to_bad_1 = "#b8cc52 None"
good_to_bad_2 = "#b8cc52 None"
good_to_bad_3 = "#95e6cb None"
good_to_bad_4 = "#95e6cb None"
good_to_bad_5 = "#ffb454 None"
good_to_bad_6 = "#ffb454 None"
good_to_bad_7 = "#ff8f40 None"
good_to_bad_8 = "#f07178 None"
good_to_bad_9 = "#f07178 None"
