# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

continuation_prompt = '▶▶ '

format = """
$os\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
${custom.giturl}\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$crystal\
$custom\
$sudo\
$line_break\
$jobs\
$battery\
$status\

$container\
$shell\
$character"""

right_format = """
$custom\
$cmd_duration\
$line_break\
$memory_usage\
$time\

"""


[directory]
truncation_length = 4
truncation_symbol = '…/'
use_os_path_sep = false
home_symbol = "~"
format = '  [$path]($style) '

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = "󰝚"
"Pictures" = ""
"Developer" = "󰲋"
"dev" = "󰲋"

[time]
disabled = false
format = '[\[ $time \]]($style) '
time_format = '%T'
utc_time_offset = 'local'

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
format = '([\[$all_status$ahead_behind\]]($style) )'

[hostname]
format = '[$ssh_symbol$hostname]($style) '
ssh_only = true

[memory_usage]
disabled = false
threshold = -1
symbol = ' '
format = '[${ram}]($style)'

[character]
success_symbol = '[❯](bold green) '
error_symbol = '[❯](bold red) '

[line_break]
disabled = false

[os]
disabled = false

[os.symbols]
Ubuntu = ""
Linux = ""
Windows = ""
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = " "
Manjaro = ""
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[cmd_duration]
format = "[]($style) [$duration]($style) "
style = "yellow"
min_time = 2_000
disabled = false

[custom.giturl]
description = "Display symbol for remote Git server"
format = "at $output "
command = '''nu -c "let r = (try { git ls-remote --get-url } catch { '' }); if ($r | str contains 'github') { echo ' ' } else if ($r | str contains 'gitlab') { echo ' ' } else if ($r | str contains 'bitbucket') { echo ' ' } else if ($r | str contains 'git') { echo ' ' } else { echo ' ' }"'''
when = 'git rev-parse --is-inside-work-tree'
